### ISSUE TITLE
Intelligent substitution

### ISSUE THREAD

**Issue by TechplexEngineer** [holygeek/git-number#20]
I'm not sure how it could be done, but the depth option on clone is taken as a value to substitute when aliasing git to git-number. Would it be crazy to add an exception to the git-number alogrithm to account for this? Are the other cases?

git clone --depth 1 https://github.com/spark/core-common-lib.git
git clone --depth application/themes/default/dashboard.html.twig https://github.com/spark/core-common-lib.git
Cloning into 'core-common-lib'...
fatal: transport: invalid depth option 'application/themes/default/dashboard.html.twig'
Unexpected end of command stream

**Comment by holygeek** [comment]
A workaround for this is to use `--depth=1`. That way git number won't see the number 1 since it is a part of a non-numeric string.
