### ISSUE TITLE
Ignore not file numbers

### ISSUE THREAD

**Issue by KES777** [holygeek/git-number#24]
Here I run git number out of git repository:
```
git-number -c rsub --port 52697 file
fatal: Not a git repository (or any of the parent directories): .git
rsub --port Please run git-number first file
There are more than one files specified. Opening only run and ignoring other.
/usr/local/bin/rsub: line 305: Please: Servname not supported for ai_socktype
/usr/local/bin/rsub: line 305: /dev/tcp/localhost/Please: Invalid argument
Unable to connect to TextMate on localhost:Please
```

1. If command is runned out of repository, you must ignore all numbers suplied  
NOTICE: 'rsub --port **Please run git-number first** file'

**Comment by holygeek** [comment]
A possible workaround for this is to use `--port=52697` instead of `--port 52697` - `git number` processes only bare numbers so it should work.
