### ISSUE TITLE
bash completion does not work

### ISSUE THREAD

**Issue by KES777** [holygeek/git-number#25]
`git-number -c git checkout 40_imple<TAB>`
expected: work at same manner as `git checkout 40_imple<TAB>`

**Comment by jonS90** [comment]
This may have more to do with [git-completion](https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks#Auto-Completion) than git-number. This discussion is relevant: http://stackoverflow.com/questions/342969/how-do-i-get-bash-completion-to-work-with-aliases.

I got completion to work okay for the alias `gn`....I *think* by added the following line in `git-completion.sh`:

```bash
complete -o default -o nospace -F _git gn
```

I believe you'd have to simplify your example to just `gn checkout 40_imple<TAB>`.

**Comment by KES777** [comment]
thank you. that work
