### ISSUE TITLE
implement numbers for `git pull`

### ISSUE THREAD

**Issue by KES777** [holygeek/git-number#29]
```
Fast-forward
 app/lib/SC/Site/Block/Feed.pm                |  9 +++++++++
 app/public/_s/css/common/all.css             |  7 +++++--
 app/public/_s/css/common/common-adaptive.css |  1 +
 app/public/_s/css/common/common-old.css      |  4 +++-
 layouts/common/common.tt                     | 17 +++++++++++++++--
 layouts/common_new/common.tt                 | 17 +++++++++++++++--
```

**Comment by holygeek** [comment]
The challenge with adding support for numbering the files presented by `git pull` is that `git pull` abbreviates the list of affected files. Another bigger issue than that is the output we see in your example above doesn't actually come from `git pull` - it came from `git merge` - `git pull` does two things `git fetch`, followed by `git merge`.

I think the complexity of hooking up `git number` into `git merge` does not worth the benefit so I'm closing this.

Do reopen this issue if there is a simpler way of achieving this.
