### ISSUE TITLE
git-number doesn't seem to work with filenames that include spaces

### ISSUE THREAD

**Issue by kaushikgopal** [holygeek/git-number#44]
```
git-number -s
```

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1042037/104779691-65a28e00-5734-11eb-96de-c16caff80b78.png">

```
git add "\".config/subl/User/Package Control.sublime-settings\""
fatal: pathspec '".config/subl/User/Package Control.sublime-settings"' did not match any files
```

<img width="783" alt="image" src="https://user-images.githubusercontent.com/1042037/104779857-aef2dd80-5734-11eb-9398-039cb4668509.png">

Does git-number not accommodate adding files through numbers, when filenames include spaces?

**Comment by holygeek** [comment]
Yes, git-number don't work with files that contains spaces in their names.
