### ISSUE TITLE
Any args given after `--' are passed to the underlying command verbatim.

### ISSUE THREAD

**Issue by KES777** [holygeek/git-number#46]
How to reproduce:
```
$ alias gl
alias gl='f(){ gn log -w -b -p --ignore-blank-lines --full-history $@; unset -f f; }; f'

$ gl 9ce3e165f284d55503eff9b627ef3723854c53bb^ -- lib/Invoice/Schema/Result/Company.pm
git log -w -b -p --ignore-blank-lines --full-history 9ce3e165f284d55503eff9b627ef3723854c53bb^ lib/Invoice/Schema/Result/Company.pm
fatal: ambiguous argument 'lib/Invoice/Schema/Result/Company.pm': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

It seems `--` is lost.
I expect command to look like: `git log -w -b -p --ignore-blank-lines --full-history 9ce3e165f284d55503eff9b627ef3723854c53bb^ -- lib/Invoice/Schema/Result/Company.pm`

Another issue here it seems that it is not possible to pass the number for `lib/Invoice/Schema/Result/Company.pm` file, eg `git log -w -b -p --ignore-blank-lines --full-history 9ce3e165f284d55503eff9b627ef3723854c53bb^ -- 7`

I need to pass file after `--` because this file was deleted and does not exists at current working directory, so I need to pass its name after `--`.

**Comment by holygeek** [comment]
Thanks for reporting this. I pushed a fix ([f7pd393](https://github.com/holygeek/git-number/commit/f70d393678b64aa0aa93d52a25e20536731308a5)) for passing down `--` to the command to be ran.

As for the second issue it's not possible to expand numbers after `--` as those will be passed intact to the command. What you can do instead is use `git-list` to expand it, e.g.: `gl -- $(git-list 7)`

**Comment by KES777** [comment]
How about `gl --- 7` feature? 

Triple `-` will mean to process string after `---` and pass result as `-- lib/Invoice/Schema/Result/Company.pm`.

This will save a lot of typing.
For comparison:
```
gl --- 7 9
gl -- $(git-list 7) $(git-list 9)
```

**Comment by holygeek** [comment]
Interesting idea! I'm not opposed to that.

**Comment by holygeek** [comment]
Something like this would work perhaps:
```
$ git diff git-number
diff --git git-number git-number
index 43f6637..bb6e59f 100755
--- git-number
+++ git-number
@@ -140,6 +140,10 @@ while (scalar @ARGV) {
         last;
     }
 
+    if ($arg eq '---') {
+        push(@args, '--');
+    }
+
     if ( $arg =~ m/^[0-9][0-9]*$/ ) {
         push @args, split("\n", `git-list $arg`);
         $converted=1;
```

Just need some unit tests and it should be good, I think.

**Comment by KES777** [comment]
Checked new version. Works fine. Thank you very much for fixes.
